/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graaa;

import org.apache.commons.math3.util.MathUtils;
        

public class App {
   

    public static void main(String[] args) {
        int n=2;
        int r=4;
        
    }
}
